import {
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
} from "recharts";

import { channelPerformance } from "../../data/dashboardData";

const ChannelPerformance = () => {
  return (
    <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6 h-full">
      <h2 className="text-xl font-semibold text-slate-800">
        Channel Performance for June
      </h2>

      <p className="text-sm text-slate-500 mb-5">
        Leads generated by each marketing channel
      </p>

      <ResponsiveContainer width="100%" height={320}>
        <BarChart data={channelPerformance}>
          <CartesianGrid strokeDasharray="3 3" />

          <XAxis dataKey="channel" />

          <YAxis />

          <Tooltip />

          <Bar dataKey="admissions" fill="#134080" radius={[8, 8, 0, 0]} />
        </BarChart>
      </ResponsiveContainer>
    </div>
  );
};

export default ChannelPerformance;
